apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/shahidraza-telespazio/argocd-demo  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD  # For Helm, this refers to the chart version.
    path: app  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
